/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Contato;
import entity.Endereco;
import entity.Pessoa;
import entity.Usuario;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import util.viaCep;


/**
 *
 * @author Fernando Kramer
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        setLocationRelativeTo(null);
        
        jtfNomeUsuario.disable();
        jpfSenha.disable();
        jpfConfSenha.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jbCadastroDePessoa = new javax.swing.JButton();
        jbCadastroDeUsuario = new javax.swing.JButton();
        jbPesquisarPessoa = new javax.swing.JButton();
        jbPesquisarUsuario = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JPanel();
        jpCadastroDePessoa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jftCpfCadastro = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeCadastro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jftDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbSexo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jftCelular = new javax.swing.JFormattedTextField();
        jcbTipoCelular = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jftTelefone = new javax.swing.JFormattedTextField();
        jcbTipoTelefone = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jftCep = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfPais = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfEstado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfUF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jbSalvarPessoa = new javax.swing.JButton();
        jbLimparPessoa = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jpCadastroDeUsuario = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jftCPFUsuario = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jtfNomeCadUsuario = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtfNomeUsuario = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jpfConfSenha = new javax.swing.JPasswordField();
        jbSalvarUsuario = new javax.swing.JButton();
        jbLimparUsuario = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jpPesquisarPessoa = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jtfcpfPesquisa = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpPesquisarUsuario = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastroDePessoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbCadastroDePessoa.setText("Cadastro de Pessoas");
        jbCadastroDePessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroDePessoaActionPerformed(evt);
            }
        });

        jbCadastroDeUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbCadastroDeUsuario.setText("Cadastro de Usuários");
        jbCadastroDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroDeUsuarioActionPerformed(evt);
            }
        });

        jbPesquisarPessoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbPesquisarPessoa.setText("Pesquisar Pessoa");
        jbPesquisarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarPessoaActionPerformed(evt);
            }
        });

        jbPesquisarUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbPesquisarUsuario.setText("Pesquisar Usuário");
        jbPesquisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCadastroDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCadastroDePessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPesquisarPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPesquisarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jbCadastroDePessoa)
                .addGap(18, 18, 18)
                .addComponent(jbCadastroDeUsuario)
                .addGap(18, 18, 18)
                .addComponent(jbPesquisarPessoa)
                .addGap(18, 18, 18)
                .addComponent(jbPesquisarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpPrincipal.setLayout(new java.awt.CardLayout());

        jpCadastroDePessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpCadastroDePessoaFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Pessoas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Dados Pessoais");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("CPF");

        try {
            jftCpfCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCpfCadastro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jftCpfCadastro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftCpfCadastroFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Nome");

        jtfNomeCadastro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Data de Nascimento");

        try {
            jftDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Sexo");

        jcbSexo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Contatos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("E-Mail");

        jtfEmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Celular");

        try {
            jftCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCelular.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jcbTipoCelular.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcbTipoCelular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Pessoal", "Comercial" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Fixo");

        try {
            jftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftTelefone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jcbTipoTelefone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcbTipoTelefone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Pessoal", "Comercial" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Endereco");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("CEP");

        try {
            jftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCep.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jftCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftCepFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Pais");

        jtfPais.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Estado");

        jtfEstado.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("U.F");

        jtfUF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Cidade");

        jtfCidade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Bairro");

        jtfBairro.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Rua");

        jtfRua.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setText("Número");

        jtfNumero.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setText("Complemento");

        jtfComplemento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jbSalvarPessoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbSalvarPessoa.setText("Salvar");
        jbSalvarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarPessoaActionPerformed(evt);
            }
        });

        jbLimparPessoa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbLimparPessoa.setText("Limpar");
        jbLimparPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroDePessoaLayout = new javax.swing.GroupLayout(jpCadastroDePessoa);
        jpCadastroDePessoa.setLayout(jpCadastroDePessoaLayout);
        jpCadastroDePessoaLayout.setHorizontalGroup(
            jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroDePessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadastroDePessoaLayout.createSequentialGroup()
                        .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                .addComponent(jbLimparPessoa)
                                .addGap(18, 18, 18)
                                .addComponent(jbSalvarPessoa))
                            .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7)
                                .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbTipoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCidade)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPais, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfEstado)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jpCadastroDePessoaLayout.setVerticalGroup(
            jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroDePessoaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jftCpfCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jcbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jtfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(74, 74, 74)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDePessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarPessoa)
                    .addComponent(jbLimparPessoa))
                .addContainerGap())
        );

        jpPrincipal.add(jpCadastroDePessoa, "Cadastro de Pessoas");

        jpCadastroDeUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jpCadastroDeUsuarioFocusGained(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Cadastro de Usuários");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Dados Pessoais");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setText("CPF");

        try {
            jftCPFUsuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftCPFUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jftCPFUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftCPFUsuarioFocusLost(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel24.setText("Nome");

        jtfNomeCadUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel25.setText("Dados de usuário");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel26.setText("Nome de Usuário");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setText("Senha");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel28.setText("Confirmação de senha");

        jtfNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jpfSenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jpfConfSenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jbSalvarUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbSalvarUsuario.setText("Salvar");
        jbSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarUsuarioActionPerformed(evt);
            }
        });

        jbLimparUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jbLimparUsuario.setText("Limpar");

        javax.swing.GroupLayout jpCadastroDeUsuarioLayout = new javax.swing.GroupLayout(jpCadastroDeUsuario);
        jpCadastroDeUsuario.setLayout(jpCadastroDeUsuarioLayout);
        jpCadastroDeUsuarioLayout.setHorizontalGroup(
            jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroDeUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addGroup(jpCadastroDeUsuarioLayout.createSequentialGroup()
                        .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addGroup(jpCadastroDeUsuarioLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftCPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpCadastroDeUsuarioLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNomeUsuario)
                    .addComponent(jpfSenha)
                    .addComponent(jpfConfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroDeUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimparUsuario)
                .addGap(18, 18, 18)
                .addComponent(jbSalvarUsuario)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroDeUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator7)
                .addContainerGap())
        );
        jpCadastroDeUsuarioLayout.setVerticalGroup(
            jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroDeUsuarioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jftCPFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jtfNomeCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(66, 66, 66)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jpfConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpCadastroDeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarUsuario)
                    .addComponent(jbLimparUsuario))
                .addContainerGap())
        );

        jpPrincipal.add(jpCadastroDeUsuario, "Cadastro de Usuarios");
        jpCadastroDeUsuario.getAccessibleContext().setAccessibleName("");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel29.setText("Pesquisar Pessoas");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel30.setText("CPF");

        try {
            jtfcpfPesquisa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfcpfPesquisa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jpPesquisarPessoaLayout = new javax.swing.GroupLayout(jpPesquisarPessoa);
        jpPesquisarPessoa.setLayout(jpPesquisarPessoaLayout);
        jpPesquisarPessoaLayout.setHorizontalGroup(
            jpPesquisarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisarPessoaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpPesquisarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8)
                    .addGroup(jpPesquisarPessoaLayout.createSequentialGroup()
                        .addGroup(jpPesquisarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addGroup(jpPesquisarPessoaLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfcpfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPesquisarPessoaLayout.setVerticalGroup(
            jpPesquisarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisarPessoaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPesquisarPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jtfcpfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpPrincipal.add(jpPesquisarPessoa, "Pesquisar Pessoa");

        javax.swing.GroupLayout jpPesquisarUsuarioLayout = new javax.swing.GroupLayout(jpPesquisarUsuario);
        jpPesquisarUsuario.setLayout(jpPesquisarUsuarioLayout);
        jpPesquisarUsuarioLayout.setHorizontalGroup(
            jpPesquisarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        jpPesquisarUsuarioLayout.setVerticalGroup(
            jpPesquisarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );

        jpPrincipal.add(jpPesquisarUsuario, "Pesquisar Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastroDePessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroDePessoaActionPerformed
        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        cl.show(jpPrincipal, "Cadastro de Pessoas");
        limparCampos();
    }//GEN-LAST:event_jbCadastroDePessoaActionPerformed

    private void jbCadastroDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroDeUsuarioActionPerformed
        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        cl.show(jpPrincipal, "Cadastro de Usuarios");
        limparCamposUsuario();
    }//GEN-LAST:event_jbCadastroDeUsuarioActionPerformed

    private void jbPesquisarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarPessoaActionPerformed
        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        cl.show(jpPrincipal, "Pesquisar Pessoa");
    }//GEN-LAST:event_jbPesquisarPessoaActionPerformed

    private void jbPesquisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarUsuarioActionPerformed
        CardLayout cl = (CardLayout) jpPrincipal.getLayout();
        cl.show(jpPrincipal, "Pesquisar Usuario");
    }//GEN-LAST:event_jbPesquisarUsuarioActionPerformed

    private void jbSalvarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarPessoaActionPerformed
        if(camposEstaoPreenchidosSalvePessoa()){
            if(jbSalvarPessoa.getText().equals("Salvar")){
                Pessoa ps = new Pessoa();
                Contato ct = new Contato();
                Endereco en = new Endereco();
                ct.setEmail(jtfEmail.getText());
                ct.setCelular(jftCelular.getText());
                ct.setTipoCelular((String) jcbTipoCelular.getSelectedItem());
                ct.setTelefone(jftTelefone.getText());
                ct.setTipoTelefone((String) jcbTipoTelefone.getSelectedItem());
                en.setCep(jftCep.getText());
                en.setPais(jtfPais.getText());
                en.setEstado(jtfEstado.getText());
                en.setUf(jtfUF.getText());
                en.setCidade(jtfCidade.getText());
                en.setBairro(jtfBairro.getText());
                en.setRua(jtfRua.getText());
                en.setNumeroCasa(Integer.parseInt(jtfNumero.getText()));
                en.setComplemento(jtfComplemento.getText());
                ps.setCpf(jftCpfCadastro.getText());
                ps.setNome(jtfNomeCadastro.getText());
                ps.setDataNascimento(jftDataNascimento.getText());
                ps.setSexo((String) jcbSexo.getSelectedItem());
                ps.setContato(ct);
                ps.setEndereco(en);
                new dao.PessoaDao().salvarCadastroPessoa(ps);
                JOptionPane.showMessageDialog(null, "Dados salvos com Sucesso!!!");
                limparCampos();
            }else{
                System.out.println(jbSalvarPessoa.getText()); 
                Pessoa ps = new Pessoa();
                Contato ct = new Contato();
                Endereco en = new Endereco();
                ct.setEmail(jtfEmail.getText());
                ct.setCelular(jftCelular.getText());
                ct.setTipoCelular((String) jcbTipoCelular.getSelectedItem());
                ct.setTelefone(jftTelefone.getText());
                ct.setTipoTelefone((String) jcbTipoTelefone.getSelectedItem());
                en.setCep(jftCep.getText());
                en.setPais(jtfPais.getText());
                en.setEstado(jtfEstado.getText());
                en.setUf(jtfUF.getText());
                en.setCidade(jtfCidade.getText());
                en.setBairro(jtfBairro.getText());
                en.setRua(jtfRua.getText());
                en.setNumeroCasa(Integer.parseInt(jtfNumero.getText()));
                en.setComplemento(jtfComplemento.getText());
                ps.setCpf(jftCpfCadastro.getText());
                ps.setNome(jtfNomeCadastro.getText());
                ps.setDataNascimento(jftDataNascimento.getText());
                ps.setSexo((String) jcbSexo.getSelectedItem());
                ps.setContato(ct);
                ps.setEndereco(en);
                new dao.PessoaDao().atualizarPessoa(ps);
                JOptionPane.showMessageDialog(null, "Dados Atualizados com Sucesso!!!");
                limparCampos();
            }
        }
    }//GEN-LAST:event_jbSalvarPessoaActionPerformed

    private void jbSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarUsuarioActionPerformed
        if(camposEstaoPreenchidosSalveUsuario()){
            String senha = util.ValidaCampo.limpaString(jpfSenha);
            String confSenha = util.ValidaCampo.limpaString(jpfConfSenha);
            if(senha.equals(confSenha)){
                if(jbSalvarUsuario.getText().trim().equals("Salvar")){
                    Pessoa ps = new dao.PessoaDao().retornarPessoa(util.ValidaCampo.limpaString(jftCPFUsuario));
                    if(ps != null){
                        Usuario us = new Usuario();
                        us.setNomeUsuario(jtfNomeUsuario.getText());
                        us.setSenha(jpfSenha.getText());
                        us.setPessoa(ps);
                        new dao.UsuarioDao().salvarUsuario(us);
                        JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!!!");
                        limparCamposUsuario();
                    }
                }else{
                    Pessoa ps = new dao.PessoaDao().retornarPessoa(util.ValidaCampo.limpaString(jftCPFUsuario));
                    if(ps != null){
                        Usuario us = new Usuario();
                        us.setNomeUsuario(jtfNomeUsuario.getText());
                        us.setSenha(jpfSenha.getText());
                        us.setPessoa(ps);
                        new dao.UsuarioDao().atualizarUsuario(us);
                        JOptionPane.showMessageDialog(null, "Usuário Atualizado com sucesso!!!");
                        limparCamposUsuario();
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "As senhas nã conferem!!!");
            }
        }else{
        }
    }//GEN-LAST:event_jbSalvarUsuarioActionPerformed

    private void jftCpfCadastroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftCpfCadastroFocusLost
        if(util.ValidaCPF.verificaCpfValido(jftCpfCadastro)){
            Pessoa ps = new dao.PessoaDao().retornarPessoa(util.ValidaCampo.limpaString(jftCpfCadastro));
            if(ps != null){
                jftCpfCadastro.setText(ps.getCpf());
                jtfNomeCadastro.setText(ps.getNome());
                jftDataNascimento.setText(ps.getDataNascimento());
                jcbSexo.setSelectedItem(ps.getSexo());
                
                jtfEmail.setText(ps.getContato().getEmail());
                jftCelular.setText(ps.getContato().getCelular());
                jcbTipoCelular.setSelectedItem(ps.getContato().getTipoCelular());
                jftTelefone.setText(ps.getContato().getTelefone());
                jcbTipoTelefone.setSelectedItem(ps.getContato().getTipoTelefone());
                
                jftCep.setText(ps.getEndereco().getCep());
                jtfPais.setText(ps.getEndereco().getPais());
                jtfEstado.setText(ps.getEndereco().getEstado());
                jtfUF.setText(ps.getEndereco().getUf());
                jtfCidade.setText(ps.getEndereco().getCidade());
                jtfBairro.setText(ps.getEndereco().getBairro());
                jtfRua.setText(ps.getEndereco().getRua());
                jtfNumero.setText(String.valueOf(ps.getEndereco().getNumeroCasa()));
                jtfComplemento.setText(ps.getEndereco().getComplemento());
                
                jftCpfCadastro.disable();
                jftDataNascimento.disable();
                jcbSexo.disable();
                jbSalvarPessoa.setText("Atualizar");
            }
        }
    }//GEN-LAST:event_jftCpfCadastroFocusLost

    private void jftCPFUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftCPFUsuarioFocusLost
        if(util.ValidaCPF.verificaCpfValido(jftCPFUsuario)){
            Pessoa ps = new dao.PessoaDao().retornarPessoa(util.ValidaCampo.limpaString(jftCPFUsuario));
            if(ps != null){
                jtfNomeCadUsuario.setText(ps.getNome());
                Usuario us = new dao.UsuarioDao().buscarUsuarioPeloIdPessoa(ps);
                if(us != null){
                    jtfNomeUsuario.setText(us.getNomeUsuario());
                    jpfSenha.setText(us.getSenha());
                    jbSalvarUsuario.setText("Atualizar");
                    jpfSenha.enable();
                    jpfSenha.requestFocus();
                    jpfConfSenha.enable();
                    jpfConfSenha.requestFocus();
                    jtfNomeUsuario.enable();
                    jtfNomeUsuario.requestFocus();
                    jftCPFUsuario.disable();
                    jtfNomeCadUsuario.disable();
                }else{
                    jbSalvarUsuario.setText("Salvar");
                    jpfSenha.enable();
                    jpfSenha.requestFocus();
                    jpfConfSenha.enable();
                    jpfConfSenha.requestFocus();
                    jtfNomeUsuario.enable();
                    jtfNomeUsuario.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(null, "O cadastro de um usuário só é permitido para pessoas já previamente cadastradas!!!");
            }
        }
    }//GEN-LAST:event_jftCPFUsuarioFocusLost

    private void jpCadastroDeUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpCadastroDeUsuarioFocusGained

    }//GEN-LAST:event_jpCadastroDeUsuarioFocusGained

    private void jftCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftCepFocusLost
        if(util.ValidaCEP.validarCep(jftCep)){
            Endereco end =  new viaCep().buscarCep(util.ValidaCampo.limpaString(jftCep));
            if(end != null){
                jtfPais.setText(end.getPais());
                jtfEstado.setText(end.getEstado());
                jtfUF.setText(end.getUf());
                jtfCidade.setText(end.getCidade());
                jtfBairro.setText(end.getBairro());
                jtfRua.setText(end.getRua());
            }else{
                JOptionPane.showMessageDialog(null, "Este cep não existe\n por gentileza verifique se o mesmo está correto!!!!");
            }
        }
    }//GEN-LAST:event_jftCepFocusLost

    private void jbLimparPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparPessoaActionPerformed
        limparCampos();
    }//GEN-LAST:event_jbLimparPessoaActionPerformed

    private void jpCadastroDePessoaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpCadastroDePessoaFocusGained

    }//GEN-LAST:event_jpCadastroDePessoaFocusGained
//------------------------------------------------------------------------------------------------------------------------    

    public boolean camposEstaoPreenchidosSalvePessoa(){
        boolean retorno = true;
            if(util.ValidaCampo.campoEstaVazio(jftCpfCadastro)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jtfNomeCadastro)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jftDataNascimento)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jtfEmail)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jftCelular)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jftCep)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jtfNumero)){
                retorno = false;
            }
        return retorno;
    }

    public boolean camposEstaoPreenchidosSalveUsuario(){
        boolean retorno = true;
            if(util.ValidaCampo.campoEstaVazio(jftCPFUsuario)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jtfNomeUsuario)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jpfSenha)){
                retorno = false;
            }
            if(util.ValidaCampo.campoEstaVazio(jpfConfSenha)){
                retorno = false;
            }
        return retorno;
    }

    public void limparCampos(){
        jftCpfCadastro.setText(null);
        jtfNomeCadastro.setText(null);
        jftDataNascimento.setText(null);
        jcbSexo.setSelectedItem("Selecione");
        jtfEmail.setText(null);
        jftCelular.setText(null);
        jcbTipoCelular.setSelectedItem("Selecione");
        jftTelefone.setText(null);
        jcbTipoTelefone.setSelectedItem("Selecione");
        jftCep.setText(null);
        jtfPais.setText(null);
        jtfEstado.setText(null);
        jtfUF.setText(null);
        jtfCidade.setText(null);
        jtfBairro.setText(null);
        jtfRua.setText(null);
        jtfNumero.setText(null);
        jtfComplemento.setText(null);
        jbSalvarPessoa.setText("Salvar");
        jftCpfCadastro.enable();
        jftDataNascimento.enable();
        jcbSexo.enable();
    }
    
    public void limparCamposUsuario(){
        jftCPFUsuario.setText(null);
        jtfNomeCadUsuario.setText(null);
        jtfNomeUsuario.setText(null);
        jpfSenha.setText(null);
        jpfConfSenha.setText(null);
        jtfNomeUsuario.disable();
        jpfSenha.disable();
        jpfConfSenha.disable();
        jftCPFUsuario.enable();
        jtfNomeCadUsuario.enable();
    }
























    
    
 //------------------------------------------------------------------------------------------------------------------------       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCadastroDePessoa;
    private javax.swing.JButton jbCadastroDeUsuario;
    private javax.swing.JButton jbLimparPessoa;
    private javax.swing.JButton jbLimparUsuario;
    private javax.swing.JButton jbPesquisarPessoa;
    private javax.swing.JButton jbPesquisarUsuario;
    private javax.swing.JButton jbSalvarPessoa;
    private javax.swing.JButton jbSalvarUsuario;
    private javax.swing.JComboBox<String> jcbSexo;
    private javax.swing.JComboBox<String> jcbTipoCelular;
    private javax.swing.JComboBox<String> jcbTipoTelefone;
    private javax.swing.JFormattedTextField jftCPFUsuario;
    private javax.swing.JFormattedTextField jftCelular;
    private javax.swing.JFormattedTextField jftCep;
    private javax.swing.JFormattedTextField jftCpfCadastro;
    private javax.swing.JFormattedTextField jftDataNascimento;
    private javax.swing.JFormattedTextField jftTelefone;
    private javax.swing.JPanel jpCadastroDePessoa;
    private javax.swing.JPanel jpCadastroDeUsuario;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPesquisarPessoa;
    private javax.swing.JPanel jpPesquisarUsuario;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPasswordField jpfConfSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfNomeCadUsuario;
    private javax.swing.JTextField jtfNomeCadastro;
    private javax.swing.JTextField jtfNomeUsuario;
    private javax.swing.JFormattedTextField jtfNumero;
    private javax.swing.JTextField jtfPais;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JTextField jtfUF;
    private javax.swing.JFormattedTextField jtfcpfPesquisa;
    // End of variables declaration//GEN-END:variables
}
